export const EXT_ID = 'advanced-code-toolkit';

export const COMMAND = {
    TOGGLE_QUOTES: `${EXT_ID}.toggle-quotes`,

    TOGGLE_CASE: `${EXT_ID}.toggle-case`,
    TOGGLE_CASE_CAMEL: `${EXT_ID}.toggle-case.camel`,
    TOGGLE_CASE_CONSTANT: `${EXT_ID}.toggle-case.constant`,
    TOGGLE_CASE_DOT: `${EXT_ID}.toggle-case.dot`,
    TOGGLE_CASE_KEBAB: `${EXT_ID}.toggle-case.kebab`,
    TOGGLE_CASE_LOWER: `${EXT_ID}.toggle-case.lower`,
    TOGGLE_CASE_LOWER_FIRST: `${EXT_ID}.toggle-case.lower-first`,
    TOGGLE_CASE_PASCAL: `${EXT_ID}.toggle-case.pascal`,
    TOGGLE_CASE_PATH: `${EXT_ID}.toggle-case.path`,
    TOGGLE_CASE_SENTENCE: `${EXT_ID}.toggle-case.sentence`,
    TOGGLE_CASE_SNAKE: `${EXT_ID}.toggle-case.snake`,
    TOGGLE_CASE_SWAP: `${EXT_ID}.toggle-case.swap`,
    TOGGLE_CASE_TITLE: `${EXT_ID}.toggle-case.title`,
    TOGGLE_CASE_UPPER: `${EXT_ID}.toggle-case.upper`,
    TOGGLE_CASE_UPPER_FIRST: `${EXT_ID}.toggle-case.upper-first`,

    TOGGLE_MULTILINE_EXPRESSION: `${EXT_ID}.toggle-multiline-expression`,

    INCREMENT_NUMBER: `${EXT_ID}.increment-number`,
    DECREMENT_NUMBER: `${EXT_ID}.decrement-number`,
} as const;

export const CONFIG = {
    HIGHLIGHT: {
        VISIBLE_RANGE_PADDING_LINES: 'highlight.visible-range-padding-lines',
    },
    TOGGLE_QUOTES: {
        QUOTES_ORDER: 'toggle-quotes.quotes-order',
    },
    TOGGLE_MULTILINE_EXPRESSION: {
        FUNCTION_TRAILING_COMMA: 'toggle-multiline-expression.function-trailing-comma',
        ARRAY_TRAILING_COMMA: 'toggle-multiline-expression.array-trailing-comma',
        OBJECT_TRAILING_COMMA: 'toggle-multiline-expression.object-trailing-comma',
    },
    COMMENT_HIGHLIGHT: {
        TAGS: 'comment-highlight.tags',
        PLAIN_TEXT: 'comment-highlight.plain-text',
        MULTILINE: 'comment-highlight.multiline',
    },
    COLOR_HIGHLIGHT: {
        ENABLED: 'color-highlight.enabled',
        MODE: 'color-highlight.mode',
        HEX: 'color-highlight.hex',
        RGB: 'color-highlight.rgb',
        HSL: 'color-highlight.hsl',
        CSS_NAMES: 'color-highlight.css-names',
        LANGUAGES: 'color-highlight.languages',
    },
} as const;

export const MESSAGE = {
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info',
};

export const COLOR_HEX_REGEX = /(^|[^A-Za-z0-9_#])(#(?:[0-9A-F]{8}|[0-9A-F]{6}|[0-9A-F]{3}))(?![A-Za-z0-9_])/ig;
export const COLOR_RGB_REGEX = /\brgba?\(\s*[^()\r\n]*\)/ig;
export const COLOR_HSL_REGEX = /\bhsla?\(\s*[^()\r\n]*\)/ig;
export const COLOR_FUNCTION_START_REGEX = /^[a-z]+\(/i;
export const COLOR_FUNCTION_END_REGEX = /\)$/;
export const COLOR_SPACE_SEPARATOR_REGEX = /\s+/;
export const COLOR_HUE_REGEX = /^([+-]?(?:\d+|\d*\.\d+))(deg|rad|turn)?$/i;

export const CSS_COLOR_NAMES: Record<string, string> = {
    aliceblue: '#f0f8ff',
    antiquewhite: '#faebd7',
    amber: '#ffbf00',
    apricot: '#fbceb1',
    aqua: '#00ffff',
    aquamarine: '#7fffd4',
    auburn: '#a52a2a',
    azure: '#f0ffff',
    babyblue: '#89cff0',
    banana: '#ffe135',
    battleshipgray: '#848482',
    beige: '#f5f5dc',
    bisque: '#ffe4c4',
    black: '#000000',
    blanchedalmond: '#ffebcd',
    blue: '#0000ff',
    blueviolet: '#8a2be2',
    blush: '#de5d83',
    bone: '#e3dac9',
    boysenberry: '#873260',
    brass: '#b5a642',
    brick: '#b22222',
    bronze: '#cd7f32',
    brown: '#a52a2a',
    buff: '#f0dc82',
    burgundy: '#800020',
    burlywood: '#deb887',
    byzantium: '#702963',
    cadetblue: '#5f9ea0',
    camel: '#c19a6b',
    cardinal: '#c41e3a',
    carmine: '#960018',
    carrot: '#ed9121',
    celadon: '#ace1af',
    cerise: '#de3163',
    cerulean: '#007ba7',
    champagne: '#f7e7ce',
    charcoal: '#36454f',
    chartreuse: '#7fff00',
    cherry: '#de3163',
    chestnut: '#954535',
    chocolate: '#d2691e',
    cinnamon: '#d2691e',
    citrine: '#e4d00a',
    claret: '#7f1734',
    cobalt: '#0047ab',
    coffee: '#6f4e37',
    copper: '#b87333',
    coquelicot: '#ff3800',
    coral: '#ff7f50',
    coralpink: '#f88379',
    corn: '#fbec5d',
    cornflowerblue: '#6495ed',
    cornsilk: '#fff8dc',
    cottoncandy: '#ffbcd9',
    cream: '#fffdd0',
    crimson: '#dc143c',
    cyan: '#00ffff',
    daffodil: '#ffff31',
    darkblue: '#00008b',
    darkcyan: '#008b8b',
    darkgoldenrod: '#b8860b',
    darkgray: '#a9a9a9',
    darkgreen: '#006400',
    darkgrey: '#a9a9a9',
    darkkhaki: '#bdb76b',
    darkmagenta: '#8b008b',
    darkolivegreen: '#556b2f',
    darkorange: '#ff8c00',
    darkorchid: '#9932cc',
    darkred: '#8b0000',
    darksalmon: '#e9967a',
    darkseagreen: '#8fbc8f',
    darkslateblue: '#483d8b',
    darkslategray: '#2f4f4f',
    darkslategrey: '#2f4f4f',
    darkturquoise: '#00ced1',
    darkviolet: '#9400d3',
    deeppink: '#ff1493',
    deepskyblue: '#00bfff',
    denim: '#1560bd',
    desert: '#c19a6b',
    dimgray: '#696969',
    dimgrey: '#696969',
    dodgerblue: '#1e90ff',
    ebony: '#555d50',
    ecru: '#c2b280',
    eggplant: '#614051',
    emerald: '#50c878',
    feldspar: '#fdd5b1',
    firebrick: '#b22222',
    flame: '#e25822',
    flax: '#eedc82',
    flesh: '#ffe9d1',
    floralwhite: '#fffaf0',
    forest: '#228b22',
    forestgreen: '#228b22',
    fuchsia: '#ff00ff',
    gainsboro: '#dcdcdc',
    gamboge: '#e49b0f',
    ghostwhite: '#f8f8ff',
    ginger: '#b06500',
    glaucous: '#6082b6',
    gold: '#ffd700',
    goldenrod: '#daa520',
    grape: '#6f2da8',
    gray: '#808080',
    green: '#008000',
    greenyellow: '#adff2f',
    grey: '#808080',
    heliotrope: '#df73ff',
    honeydew: '#f0fff0',
    hotpink: '#ff69b4',
    iceberg: '#71a6d2',
    indianred: '#cd5c5c',
    indigo: '#4b0082',
    iris: '#5a4fcf',
    jade: '#00a86b',
    jasmine: '#f8de7e',
    jet: '#343434',
    jonquil: '#fada5e',
    ivory: '#fffff0',
    khaki: '#f0e68c',
    lava: '#cf1020',
    lavender: '#e6e6fa',
    lavenderblush: '#fff0f5',
    lavenderpurple: '#967bb6',
    lawngreen: '#7cfc00',
    lemon: '#fff700',
    lemonchiffon: '#fffacd',
    licorice: '#1a1110',
    lightblue: '#add8e6',
    lightcoral: '#f08080',
    lightcyan: '#e0ffff',
    lightgoldenrodyellow: '#fafad2',
    lightgray: '#d3d3d3',
    lightgreen: '#90ee90',
    lightgrey: '#d3d3d3',
    lightpink: '#ffb6c1',
    lightsalmon: '#ffa07a',
    lightseagreen: '#20b2aa',
    lightskyblue: '#87cefa',
    lightslategray: '#778899',
    lightslategrey: '#778899',
    lightsteelblue: '#b0c4de',
    lightyellow: '#ffffe0',
    lilac: '#c8a2c8',
    lime: '#00ff00',
    limegreen: '#32cd32',
    linen: '#faf0e6',
    lion: '#c19a6b',
    liver: '#674c47',
    lust: '#e62020',
    magenta: '#ff00ff',
    magnolia: '#f8f4ff',
    mahogany: '#c04000',
    maize: '#fbec5d',
    malachite: '#0bda51',
    mango: '#fdbe02',
    mantis: '#74c365',
    maroon: '#800000',
    mauve: '#e0b0ff',
    mediumaquamarine: '#66cdaa',
    mediumblue: '#0000cd',
    mediumorchid: '#ba55d3',
    mediumpurple: '#9370db',
    mediumseagreen: '#3cb371',
    mediumslateblue: '#7b68ee',
    mediumspringgreen: '#00fa9a',
    mediumturquoise: '#48d1cc',
    mediumvioletred: '#c71585',
    melon: '#febaad',
    midnight: '#702670',
    midnightblue: '#191970',
    mikado: '#ffc40c',
    mimosa: '#ffca4b',
    mint: '#98ff98',
    mindaro: '#e3f988',
    mintcream: '#f5fffa',
    mistyrose: '#ffe4e1',
    moccasin: '#ffe4b5',
    mocha: '#bea493',
    moss: '#8a9a5b',
    mountbattenpink: '#997a8d',
    mulberry: '#c54b8c',
    mustard: '#ffdb58',
    myrtle: '#21421e',
    navajowhite: '#ffdead',
    navy: '#000080',
    nickel: '#727472',
    nude: '#f2d6c6',
    nyanza: '#e9ffdb',
    ochre: '#cc7722',
    oldlace: '#fdf5e6',
    olive: '#808000',
    olivedrab: '#6b8e23',
    olivine: '#9ab973',
    onyx: '#353839',
    opal: '#a8c3bc',
    orange: '#ffa500',
    orangered: '#ff4500',
    orchid: '#da70d6',
    oxblood: '#4a0404',
    oyster: '#d0caae',
    patina: '#639a8f',
    palegoldenrod: '#eee8aa',
    palegreen: '#98fb98',
    paleturquoise: '#afeeee',
    palevioletred: '#db7093',
    papayawhip: '#ffefd5',
    peach: '#ffe5b4',
    peachpuff: '#ffdab9',
    pear: '#d1e231',
    pearl: '#eae0c8',
    peridot: '#e6e200',
    persimmon: '#ec5800',
    peru: '#cd853f',
    petrol: '#005f6a',
    pink: '#ffc0cb',
    pine: '#01796f',
    pistachio: '#93c572',
    platinum: '#e5e4e2',
    plum: '#dda0dd',
    porcelain: '#f2fbfc',
    powderblue: '#b0e0e6',
    puce: '#cc8899',
    pumpkin: '#ff7518',
    purple: '#800080',
    quartz: '#51484f',
    quicksilver: '#a6a6a6',
    raspberry: '#e30b5d',
    rawumber: '#826644',
    razzmatazz: '#e3256b',
    rebeccapurple: '#663399',
    red: '#ff0000',
    redwood: '#a45a52',
    rhodamine: '#e6007e',
    riflegreen: '#444c38',
    robin: '#00cccc',
    rose: '#ff007f',
    rosewood: '#65000b',
    rosybrown: '#bc8f8f',
    rouge: '#a23b6c',
    royalblue: '#4169e1',
    ruby: '#e0115f',
    russet: '#80461b',
    rust: '#b7410e',
    saddlebrown: '#8b4513',
    saffron: '#f4c430',
    sage: '#bcb88a',
    salmon: '#fa8072',
    sand: '#c2b280',
    sandybrown: '#f4a460',
    sangria: '#92000a',
    sapphire: '#0f52ba',
    scarlet: '#ff2400',
    seagreen: '#2e8b57',
    seashell: '#fff5ee',
    sepia: '#704214',
    shamrock: '#009e60',
    shell: '#ffb6c1',
    sienna: '#a0522d',
    silver: '#c0c0c0',
    sinopia: '#cb410b',
    skyblue: '#87ceeb',
    slateblue: '#6a5acd',
    slategray: '#708090',
    slategrey: '#708090',
    smalt: '#003399',
    smoke: '#738276',
    snow: '#fffafa',
    sorrel: '#c38d4d',
    springgreen: '#00ff7f',
    steel: '#71797e',
    steelblue: '#4682b4',
    straw: '#e4d96f',
    sulfur: '#e8ed5b',
    sunglow: '#ffcc33',
    sunset: '#fad6a5',
    tan: '#d2b48c',
    taupe: '#483c32',
    teal: '#008080',
    terracotta: '#e2725b',
    thistle: '#d8bfd8',
    titanium: '#878681',
    tomato: '#ff6347',
    topaz: '#ffc87c',
    turquoise: '#40e0d0',
    tuscany: '#c09999',
    ultramarine: '#3f00ff',
    umber: '#635147',
    vanilla: '#f3e5ab',
    venetianred: '#c80815',
    verdigris: '#43b3ae',
    vermilion: '#e34234',
    veronica: '#a020f0',
    violet: '#ee82ee',
    viridian: '#40826d',
    walnut: '#773f1a',
    wenge: '#645452',
    wine: '#722f37',
    wisteria: '#c9a0dc',
    wheat: '#f5deb3',
    white: '#ffffff',
    whitesmoke: '#f5f5f5',
    xanadu: '#738678',
    yellow: '#ffff00',
    yellowgreen: '#9acd32',
    zaffre: '#0014a8',
    zomp: '#39a78e',
};

const CSS_COLOR_NAME_PATTERN = Object.keys(CSS_COLOR_NAMES)
    .sort((a, b) => b.length - a.length)
    .join('|');

export const CSS_COLOR_NAME_REGEX = new RegExp(
    `(^|[^A-Za-z0-9_-])(${CSS_COLOR_NAME_PATTERN})(?![A-Za-z0-9_-])`,
    'ig',
);

export const CASE_WORD_CHARACTER_REGEX = /([\w_\-\/]+)/;

export const CASE = {
    CAMEL: 'camel',
    CONSTANT: 'constant',
    DOT: 'dot',
    KEBAB: 'kebab',
    LOWER: 'lower',
    LOWER_FIRST: 'lowerFirst',
    PASCAL: 'pascal',
    PATH: 'path',
    SENTENCE: 'sentence',
    SNAKE: 'snake',
    SWAP: 'swap',
    TITLE: 'title',
    UPPER: 'upper',
    UPPER_FIRST: 'upperFirst',
};

export const MULTILINE_SIGNATURE_OPENING_BRACE_REGEX = /^[ \t]*(:[^\r\n{]+)?\r?\n[ \t]*\{/;
export const MULTILINE_NEXT_LINE_OPENING_BRACE_REGEX = /\r?\n[ \t]*\{$/;
export const MULTILINE_SAME_LINE_OPENING_BRACE_REGEX = /^[ \t]*(:[^\r\n{]+)?[ \t]*\{/;
